apiVersion: v1
kind: Service
metadata:
  name: peer0-couchdb-airbus
  labels: { component: peer0, type: couchdb, org: airbus }
spec:
  type: ClusterIP
  selector:
    component: peer0
    type: couchdb
    org: airbus
  ports:
    - port: 5984
      targetPort: 5984
