apiVersion: v1
kind: Service
metadata:
  name: regulator-ca-root
  labels: { component: root, type: ca-server, org: regulator }
spec:
  type: ClusterIP
  selector:
    component: root
    type: ca-server
    org: regulator
  ports:
    - port: 7054
      targetPort: 7054
