apiVersion: v1
kind: Service
metadata:
  name: api-server-general-service
  labels: { component: server, type: api, org: general }
spec:
  type: ClusterIP
  selector:
    component: server
    type: api
    org: general
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-general-nodeport
spec:
  type: NodePort
  selector:
    component: server
    type: api
    org: general
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
