apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: general-persistent-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
