apiVersion: v1
kind: Service
metadata:
  name: general-ca-root
  labels: { component: root, type: ca-server, org: general }
spec:
  type: ClusterIP
  selector:
    component: root
    type: ca-server
    org: general
  ports:
    - port: 7054
      targetPort: 7054
