apiVersion: v1
kind: Service
metadata:
  name: peer0-general-service
  labels: { component: peer0, type: peer, org: general }
spec:
  type: ClusterIP
  selector:
    component: peer0
    type: peer
    org: general
  ports:
    - port: 7051
      targetPort: 7051
      name: gossip
    - port: 9443
      targetPort: 9443
      name: operations
