apiVersion: v1
kind: Service
metadata:
  name: api-server-airbus-service
  labels: { component: server, type: api, org: airbus }
spec:
  type: ClusterIP
  selector:
    component: server
    type: api
    org: airbus
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-airbus-nodeport
spec:
  type: NodePort
  selector:
    component: server
    type: api
    org: airbus
  ports:
    - port: 4050
      targetPort: 4000
      nodePort: 31516
