apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-airbus-deployment
  labels: { component: peer0, type: peer, org: airbus }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer0
      type: peer
      org: airbus
  template:
    metadata:
      labels:
        component: peer0
        type: peer
        org: airbus
    spec:
      volumes:
        - name: airbus-pv-mount
          persistentVolumeClaim:
            claimName: airbus-persistent-volume-claim
        # - name: network-pv-mount
        #   persistentVolumeClaim:
        #     claimName: network-persistent-volume-claim
        - name: host
          hostPath:
            path: /var/run
      containers:
        - name: peer0-airbus
          image: hyperledger/fabric-peer:2.0.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["peer"]
          args: ["node", "start"]
          env:
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_VM_ENDPOINT
              value: unix:///var/run/docker.sock
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_VM_DOCKER_ATTACHOUT
              value: "true"
            - name: CORE_PEER_ID
              value: peer0-airbus-service
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-airbus-service:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0-airbus-service:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer0-airbus-service:7051
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052
            - name: CORE_PEER_LOCALMSPID
              value: AirbusMSP
            - name: CORE_PEER_ENDORSER_ENABLED
              value: "true"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: peer0-couchdb-airbus:5984
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: CouchDB
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              value: newuser
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              value: "1234"
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: "0.0.0.0:9443"
            - name: CORE_METRICS_PROVIDER
              value: prometheus
          volumeMounts:
            - mountPath: /var/run
              name: host
            - mountPath: /etc/hyperledger/fabric/msp
              name: airbus-pv-mount
              subPath: state/airbus-ca-client/peers/peer0.airbus.parttracer.com/msp
            - mountPath: /etc/hyperledger/fabric/tls
              name: airbus-pv-mount
              subPath: state/airbus-ca-client/peers/peer0.airbus.parttracer.com/tls
            # - name: network-pv-mount
            #   mountPath: /var/hyperledger/peer0/data
            #   subPath: artifacts/channel-artifacts
            # - mountPath: /var/hyperledger/production
            #   name: host-mount
            #   subPath: state/airbus/peers/peer0
            # - mountPath: /scripts
            #   name: host-mount
            #   subPath: files/scripts
