apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbus-persistent-volume-claim
spec:
  storageClassName: gcp-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
