apiVersion: v1
kind: Service
metadata:
  name: airbus-ca-root
  labels: { component: root, type: ca-server, org: airbus }
spec:
  type: ClusterIP
  selector:
    component: root
    type: ca-server
    org: airbus
  ports:
    - port: 7054
      targetPort: 7054
